workflows:
  kaify-ios:
    name: Kaify iOS
    instance_type: mac_mini_m2
    max_build_duration: 120

    integrations:
      app_store_connect: Kaify

    environment:
      ios_signing:
        provisioning_profiles:
          - kaify_appstore_profile
        certificates:
          - kaify_distribution
