/**
 * Disposable email domain listesi.
 * Risk seviyelerine göre kategorize edilmiştir:
 * - high: Kesinlikle block (spam/tuzak domainler)
 * - medium: Şüpheli, log + allow (şimdilik)
 *
 * Bakım: Yeni disposable domain'ler keşfedildikçe bu listeye ekleyin.
 * Kaynak: https://github.com/disposable-email-domains/disposable-email-domains
 */

// En yaygın ~150 disposable email domaini
const HIGH_RISK_DOMAINS: string[] = [
  "10minutemail.com", "10minutemail.net", "10minutemail.org",
  "guerrillamail.com", "guerrillamail.net", "guerrillamail.org",
  "guerrillamail.de", "guerrillamail.info", "guerrillamail.biz",
  "guerillamail.com", "guerillamail.net", "guerillamail.org",
  "guerillamail.de", "guerillamail.info", "guerillamail.biz",
  "mailinator.com", "mailinator.net", "mailinator.org",
  "yopmail.com", "yopmail.fr", "yopmail.net",
  "tempmail.com", "tempmail.net", "tempmail.org",
  "throwaway.email", "throwawaymail.com",
  "getnada.com", "nada.email", "nada.ltd",
  "maildrop.cc", "maildrop.io",
  "sharklasers.com", "sharklasers.net",
  "trashmail.com", "trashmail.net", "trashmail.org",
  "trashmail.de", "trashmail.me",
  "temp-mail.org", "temp-mail.net", "temp-mail.com",
  "tempemail.co", "tempemail.net", "tempemail.org",
  "dispostable.com", "disposableinbox.com",
  "spambox.us", "spambox.info", "spambox.me",
  "spamgourmet.com", "spamgourmet.net", "spamgourmet.org",
  "spamhole.com", "spamhole.net",
  "spam.la", "spam.su",
  "mailexpire.com", "mailexpire.net",
  "mailcatch.com", "mailcatch.net",
  "mailnesia.com", "mailinator2.com",
  "mintemail.com", "mobileninja.co.uk",
  "mytrashmail.com", "mytrashmail.net",
  "neverbox.com", "neverbox.net",
  "nowmymail.com", "nowmymail.net",
  "oneoffmail.com", "oneoffmail.net",
  "owlymail.com", "owlymail.net",
  "pookmail.com", "pookmail.net",
  "proxymail.eu", "proxymail.info",
  "quickinbox.com", "quickinbox.net",
  "rcpt.at", "rcpt.net",
  "receiveee.com", "receiveee.net",
  "recyclemail.com", "recyclemail.net",
  "regbypass.com", "regbypass.net",
  "sneakemail.com", "sneakemail.net",
  "sofort-mail.de", "sofort-mail.net",
  "spamfree24.org", "spamfree24.net",
  "spamherelots.com", "spamherelots.net",
  "spamlot.net", "spamlot.org",
  "spamobox.com", "spamobox.net",
  "spamslicer.com", "spamslicer.net",
  "spamthis.co.uk", "spamthis.net",
  "spamtrail.com", "spamtrail.net",
  "spamwc.de", "spamwc.net",
  "spoofmail.de", "stuffmail.de",
  "sudolife.me", "sudolife.net",
  "suioe.com", "suioe.net",
  "supergreatmail.com", "supergreatmail.net",
  "supermailer.jp", "supermailer.net",
  "suremail.info", "suremail.net",
  "temporaryemail.us", "temporaryemail.net",
  "temporaryforwarding.com", "temporaryforwarding.net",
  "temporaryinbox.com", "temporaryinbox.net",
  "thisisnotmyrealemail.com",
  "throwawayemail.com", "throwawayemail.net",
  "tilien.com", "tilien.net",
  "tittbit.in", "tittbit.net",
  "tizi.com", "tizi.net",
  "tmail.ws", "tmail.net",
  "toomail.com", "toomail.net",
  "trash2009.com", "trash2009.net",
  "trashdevil.com", "trashdevil.net",
  "trashymail.com", "trashymail.net", "trashymail.org",
  "tyldd.com", "tyldd.net",
  "uggsrock.com", "uggsrock.net",
  "umail.net", "umail.org",
  "upliftnow.com", "upliftnow.net",
  "uplipht.com", "uplipht.net",
  "venompen.com", "venompen.net",
  "veryrealemail.com", "veryrealemail.net",
  "vidchart.com", "vidchart.net",
  "viewcastmedia.com", "viewcastmedia.net", "viewcastmedia.org",
  "viralplays.com", "viralplays.net",
  "vsimcard.com", "vsimcard.net",
  "vubby.com", "vubby.net",
  "walala.org", "walala.net",
  "walkmail.net", "walkmail.org",
  "webm4il.info", "webm4il.net",
  "wegwerfmail.de", "wegwerfmail.net", "wegwerfmail.org",
  "wh4f.org", "wh4f.net",
  "whyspam.me", "whyspam.net",
  "willselfdestruct.com", "willselfdestruct.net",
  "winemaven.info", "winemaven.net",
  "wronghead.com", "wronghead.net",
  "wuzup.net", "wuzup.org",
  "xagloo.com", "xagloo.net",
  "xemaps.com", "xemaps.net",
  "xents.com", "xents.net",
  "xmaily.com", "xmaily.net",
  "xoxy.net", "xoxy.org",
  "xwaretech.com", "xwaretech.net",
  "xww.ro", "xww.net",
  "yep.it", "yep.net",
  "yogamaven.com", "yogamaven.net",
  "yopmail.fr", "yopmail.net",
  "yuurok.com", "yuurok.net",
  "zehnminutenmail.de", "zehnminutenmail.net",
  "zetmail.com", "zetmail.net",
  "zippymail.info", "zippymail.net",
  "zoaxe.com", "zoaxe.net",
  "zoemail.org", "zoemail.net",
  "zomg.info", "zomg.net",
  "zumpat.com", "zumpat.net",
  "zxcv.com", "zxcv.net",
  "zxcvbnm.com", "zxcvbnm.net",
  "zzz.com", "zzz.net",
  "0-mail.com", "027168.com", "0815.ru",
  "0clickemail.com", "0wnd.net", "0wnd.org",
  "1ce.us", "1chuan.com", "1mail.ml", "1pad.de",
  "1shivom.com", "1usemail.com",
  "2-mail.com", "20email.eu", "20mail.it", "2prong.com",
  "3-mail.com", "3l6.com",
  "4-mail.com", "4mail.cf", "4mail.ga",
  "4warding.com", "4warding.net", "4warding.org",
  "5-mail.com", "5oz.ru", "5x25.com",
  "6-mail.com", "6ip.us", "6paq.com",
  "7-mail.com", "8-mail.com",
  "9-mail.com", "9ox.net",
  "a-bc.net", "a45.in",
  "abusemail.de", "abyssemail.com", "abyssmail.com",
  "afrobacon.com", "agedmail.com", "akapost.com",
  "amail.com", "amail4.me", "amilegit.com",
  "ano-mail.net", "anon-mail.de", "anonbox.net",
  "anonymail.dk", "anonymbox.com", "anonymized.org",
  "antireg.ru", "antispam24.de", "armyspy.com",
  "asdasd.nl", "asdasd.ru", "auti.st",
  "aver.com", "axiz.org",
  "b1of96u.com", "b2bx.net", "badoop.com",
  "bcast.ws", "bcb.ro", "beddly.com", "beefmilk.com",
  "bettamail.com", "big1.us", "bigstring.com",
  "binka.me", "binkmail.com", "binnary.com",
  "bio-muesli.net", "biz.st", "bladesmail.net",
  "blogmyway.org", "bluebottle.com", "bnote.com",
  "bobmail.info", "bonobo.email", "bootybay.de",
  "borged.com", "bot.nu", "boun.cr", "bouncr.com",
  "boxformail.com", "boximail.com", "boxtemp.com.br",
  "brandallday.net", "breakthru.com", "brefmail.com",
  "bsnow.net", "buffemail.com", "bugmenot.com",
  "bum.net", "bumpymail.com", "bunchofidiots.com",
  "bund.us", "bunsenhoneydew.com", "burnthespam.info",
  "buyusedlibrarybooks.org", "byebyemail.com", "byespm.com",
  "c2.hu", "cachedot.net", "candymail.de",
  "card.zp.ua", "caseedu.tk",
  "cellurl.com", "centermail.com", "centermail.net",
  "cetpass.com", "chacuo.net", "chammy.info",
  "cheaphub.net", "cheatmail.de", "chickenkiller.com",
  "chielo.com", "chilkat.com", "chithi.xyz",
  "choco.la", "chogmail.com",
  "cigar-auctions.com", "ckiso.com", "clandest.in",
  "clipmail.eu", "clrmail.com", "cmail.club", "cmail.com",
  "cnamed.com", "cnew.ir", "co.cc",
  "cock.li", "codeandscotch.com", "coldemail.info",
  "consumerriot.com", "cool.fr.nf", "coolandwacky.us",
  "courrieltemporaire.com", "crankymonkey.info",
  "crapmail.org", "crastination.de", "crazymailing.com",
  "cream.pink", "crossroadsmail.com", "crusthost.com",
  "cryp.email", "crypter.email", "cubiclink.com",
  "cuemail.com", "curryworld.de", "cust.in",
  "cutout.club", "cuvox.de", "cylab.org",
  "dab.ro", "dacoolest.com", "dandikmail.com",
  "dayrep.com", "dcemail.com", "deadaddress.com",
  "deadfake.cf", "deadfake.ga", "deadfake.ml",
  "deadspam.com", "deagot.com", "dealja.com",
  "delikkt.de", "despam.it", "despammed.com",
  "dev-null.cf", "dev-null.ga", "dev-null.ml",
  "devnullmail.com", "dfg.net", "dfgh.net",
  "digdown.xyz", "digitalsanctuary.com",
  "dingbone.com", "discard.cf", "discard.email",
  "discard.ga", "discard.gq", "discard.ml",
  "discardmail.com", "discardmail.de",
  "disign-concept.eu", "disign-revelation.com",
  "dispo.in", "dispomail.eu", "disposable-email.ml",
  "disposable.cf", "disposable.ga", "disposable.ml",
  "disposableaddress.com", "disposablemails.com",
  "dispose.it", "disposeamail.com", "disposemail.com",
  "divermail.com", "divismail.ru", "dlemail.com",
  "dlemail.ru", "dmarc.ro", "dndent.com",
  "dodgeit.com", "dodgemail.de", "dodgit.com",
  "dodgit.org", "dolphinnet.net", "donemail.ru",
  "dontreg.com", "dontsendmespam.de", "dotman.de",
  "doublemail.de", "drdrb.com", "drdrb.net",
  "dred.ru", "drf.email", "drmail.pw",
  "droidemail.com", "dudmail.com", "dump-email.info",
  "dumpandjunk.com", "dumpmail.com", "dumpmail.de",
  "dumpyemail.com", "duskmail.com", "dz17.net",
  "e-mail.com", "e-mail.org", "e3z.de", "e4ward.com",
  "easy-trash-mail.com", "easytrashmail.com",
  "ebeschlussbuch.de", "edgex.ru", "edv.to",
  "eelmail.com", "efxs.ca", "einmalmail.de",
  "einrot.com", "einrot.de", "eintagsmail.de",
  "email-fake.cf", "email-fake.ga", "email-fake.gq",
  "email-fake.ml", "email-fake.tk", "email-jetable.fr",
  "email-lab.com", "email-temp.com", "email60.com",
  "emailage.cf", "emailage.ga", "emailage.gq",
  "emailage.ml", "emaildienst.de", "emaildrop.io",
  "emailfake.ml", "emailfake.tk", "emailfreedom.ml",
  "emailgo.de", "emailias.com", "emailinfive.com",
  "emaillime.com", "emailmiser.com", "emailna.co",
  "emailna.life", "emailnax.com", "emailo.pro",
  "emailondeck.com", "emailportal.info",
  "emailr.win", "emailresort.com", "emailsecurer.com",
  "emailsensei.com", "emailsingularity.net",
  "emailsy.info", "emailtemporanea.com",
  "emailtemporanea.net", "emailtemporar.ro",
  "emailtemporario.com.br", "emailtmp.com",
  "emailto.de", "emailure.net", "emailwarden.com",
  "emailx.at", "emailxfer.com", "emeil.in",
  "emeil.ir", "emil.com", "emlhub.com",
  "emlpro.com", "emltmp.com", "enayu.com",
  "enterto.com", "epb.ro", "eposta.work",
  "ereply.me", "ero-tube.org", "esc.la",
  "escapehatchapp.com", "esemay.com", "esgeneri.com",
  "etranquil.com", "etranquil.net", "etranquil.org",
  "euaqa.com", "everyone.net", "evopo.com",
  "exbte.com", "existiert.net", "explodemail.com",
  "extremail.ru", "eyepaste.com", "ez.lv",
  "facebook-email.cf", "facebook-email.ga", "facebook-email.ml",
  "fackme.gq", "failbone.com",
  "fake-email.pp.ua", "fake-mail.cf", "fake-mail.ga", "fake-mail.ml",
  "fakedemail.com", "fakeinbox.cf", "fakeinbox.ga",
  "fakeinbox.ml", "fakeinbox.tk", "fakeinformation.com",
  "fakemail.fr", "fakemail.win", "fakemailgenerator.com",
  "fakemailz.com", "fammix.com", "fangoh.com",
  "fantasymail.de", "farrse.co.uk",
  "fastacura.com", "fastchevy.com", "fastchrysler.com",
  "fastkawasaki.com", "fastmazda.com", "fastmitsubishi.com",
  "fastnissan.com", "fastsubaru.com", "fastsuzuki.com",
  "fasttoyota.com", "fastyamaha.com", "fatflap.com",
  "fer-gabon.org", "fettometern.com", "fightallspam.com",
  "figjs.com", "figshot.com", "filzmail.com",
  "fir.hk", "firemail.cc", "fivemail.de",
  "fixmail.tk", "flemail.ru", "flurre.com",
  "flyspam.com", "foobarbot.net", "footard.com",
  "forgetmail.com", "fornow.eu", "forward.cat",
  "fr33mail.info", "frapmail.com",
  "free-email.cf", "free-email.ga",
  "freecat.net", "freedompop.us",
  "freeletter.me", "freemail.ms",
  "freemails.cf", "freemails.ga", "freemails.ml",
  "friendlymail.co.uk", "front14.org",
  "fuckedupload.com", "fuckingduh.com",
  "fudgerub.com", "fulvie.com", "funnymail.de",
  "fuwamofu.com", "fux0ringduh.com", "fyii.de",
  "gafy.net", "gaggle.net", "game.com",
  "garasikita.pw", "garbagecollector.org",
  "garbagemail.org", "garliclife.com",
  "gawab.com", "geekforex.com", "gelitik.in",
  "genderfuck.net", "geronra.com",
  "get-mail.cf", "get-mail.ga", "get-mail.ml",
  "get.pp.ua", "get1mail.com", "get2mail.fr",
  "getairmail.cf", "getairmail.ga", "getairmail.gq",
  "getairmail.ml", "getairmail.tk", "getamailbox.com",
  "geteit.com", "getmails.eu",
  "getnowmail.com", "getonemail.com", "getonemail.net",
  "getsimpleemail.com", "ghosttexter.de",
  "giantmail.de", "gishpuppy.com",
  "glitch.sx", "glubex.com", "glucosegrin.com",
  "gmailxmail.com", "golemico.com", "gomail.in",
  "googlegroups.com", "gorillaswithdirtyarmpits.com",
  "goshdarnspam.com", "gothere.biz",
  "gotmail.com", "gotmail.net", "gotmail.org",
  "grandmamail.com", "grandmasmail.com",
  "greendike.com", "greenhousemail.com",
  "greggamel.com", "greggamel.net",
  "gregorygamel.com", "gregorygamel.net",
  "grish.de", "grr.la",
  "gustr.com", "h8s.org",
  "habitue.net", "hackthatbit.ch",
  "hahawrong.com", "hailmail.net",
  "haltospam.com", "handy.com",
  "hanteml.com", "hatespam.org",
  "haydoo.com", "hazelnut4u.com", "hazelnuts4u.com",
  "headstrong.de", "heathenhammer.com", "heathenhero.com",
  "hellodream.mobi", "helloricky.com",
  "herp.in", "herpderp.nl",
  "hezll.com", "hi5.si",
  "hiddentragedy.com", "hidebox.org",
  "hidemail.de", "hidemail.pro", "hidemail.us",
  "hidzz.com", "highbrow.org",
  "hmail.us", "hmamail.com",
  "hochsitze.com", "honeys.be",
  "hopemail.biz", "hostcalls.com",
  "hotmai.com", "hotmail.red",
  "hotpop.com", "housat.com",
  "hstermail.com", "hu2.ru",
  "hulapla.de", "humaility.com",
  "hungpackage.com", "hushmail.com",
  "i2pmail.org", "iaoss.com",
  "icantbelieveineedtoexplainthisshit.com",
  "ichigo.me", "icx.in", "icx.ro",
  "ieatspam.eu", "ieatspam.info",
  "igg.biz", "ignoremail.com",
  "ihateyoualot.info", "ihazspam.ca",
  "iheartspam.org", "illistnoise.com",
  "ilovespam.com", "imails.info",
  "imgof.com", "inaby.com",
  "inapplicable.org", "inbax.tk",
  "inbox.si", "inboxalias.com",
  "inboxclean.com", "inboxclean.org",
  "inboxdesign.me", "inboxed.pw",
  "inboxhub.net", "inboxkitten.com",
  "inclusiveprogress.com", "incognitomail.com",
  "incognitomail.net", "incognitomail.org",
  "incq.com", "ind.st",
  "indieclad.com", "indirect.ws",
  "indusspam.com", "ineec.net",
  "infest.org", "infomedia.icu",
  "inggo.org", "inoutmail.de",
  "inoutmail.eu", "inoutmail.info",
  "inoutmail.net", "insorg-mail.info",
  "instaddr.ch", "instmail.net",
  "internetkeno.com", "interstats.org",
  "intersteller.com", "ipoo.org",
  "ipsur.org", "irish2me.com",
  "iroid.com", "irssi.tv",
  "isdaq.com", "isosq.com",
  "ist-allein.info", "ist-einmalig.de",
  "ist-willig.de", "it7.ovh",
  "ivyro.net", "ixx.io",
  "jajxz.com", "jaqis.com",
  "jetable.com", "jetable.fr.nf",
  "jetable.net", "jetable.org",
  "jetable.pp.ua", "jmail.ovh",
  "jmail.ro", "joelpet.com",
  "jopho.com", "jourrapide.com",
  "jredm.com", "junk.to",
  "junk1e.com", "junkmail.com",
  "junkmail.gq", "junkmail.org",
  "jupimail.com", "justbegood.net",
  "k-posti.com", "kademen.com",
  "kagi.be", "kakadua.net",
  "kamsg.com", "kaovo.com",
  "kappala.info", "karbasi.com",
  "kaspop.com", "katztube.com",
  "kcrw.de", "keepmymail.com",
  "keinpardon.de", "kekita.com",
  "kiani.com", "killmail.com",
  "killmail.net", "kimsdisk.com",
  "kinkh.com", "kisshq.com",
  "klassmaster.com", "klassmaster.net",
  "kloap.com", "kludgemush.com",
  "kmhow.com", "knol-power.nl",
  "kobrandly.com", "kon42.com",
  "kopagas.com", "kopaka.net",
  "kostenlosmail.de", "koszmail.pl",
  "krd.ag", "krd.ws",
  "kuhrap.com", "kurzepost.de",
  "kwift.net", "kwilco.net",
  "l33r.eu", "l6factors.com",
  "labetteraverouge.at", "labworld.org",
  "lacedmail.com", "lackmail.net",
  "lackmail.ru", "lacto.info",
  "lain.ch", "lakqs.com",
  "landmail.co", "laoeq.com",
  "last-chance.pro", "lastmail.co",
  "lastmail.com", "lawlita.com",
  "lazyinbox.com", "lazyinbox.us",
  "ldop.com", "ldtp.com",
  "lee.mx", "leeching.net",
  "leermail.com", "lefarceur.fr",
  "lerch.ovh", "letthemeatspam.com",
  "lez.se", "lg4e.com",
  "liamcyrus.com", "lifetimefriends.info",
  "likesyouback.com", "lillemap.net",
  "lilo.me", "link2mail.net",
  "linuxmail.so", "litedrop.com",
  "lkgn.se", "llogin.ru",
  "loadby.us", "localgenius.com",
  "lockmail.us", "logans.com",
  "login-email.cf", "login-email.ga",
  "login-email.ml", "login-email.tk",
  "loh.pp.ua", "loin.in",
  "lolfreak.net", "lolpost.com",
  "lookugly.com", "lortemail.dk",
  "losemymail.com", "lovemeleaveme.com",
  "lr7.us", "lroid.com",
  "lru.me", "lukop.dk",
  "luv2.us", "m4ilweb.info",
  "maboard.com", "macromaid.com",
  "magamail.com", "magicbox.ro",
  "mail-card.com", "mail-cart.com",
  "mail-drive.net", "mail-filter.com",
  "mail-owl.com", "mail-share.com",
  "mail-temp.com", "mail-temporaire.com",
  "mail-temporaire.fr", "mail.by",
  "mail114.net", "mail1a.de",
  "mail21.cc", "mail2rss.org",
  "mail333.com", "mail4trash.com",
  "mail666.ru", "mail707.com",
  "mail72.com", "mailback.com",
  "mailbidon.com", "mailbiz.biz",
  "mailblocks.com", "mailbucket.org",
  "mailcat.biz", "mailcatch.com",
  "mailcell.net", "mailcity.com",
  "mailcker.com", "mailde.de",
  "mailde.info", "maildrop.cc",
  "maileater.com", "mailed.in",
  "maileimer.de", "mailexpire.com",
  "mailfa.tk", "mailforspam.com",
  "mailfree.ga", "mailfree.gq",
  "mailfree.ml", "mailfs.com",
  "mailguard.me", "mailgutter.com",
  "mailhazard.com", "mailhazard.us",
  "mailhex.com", "mailhub.pro",
  "mailhz.me", "mailimate.com",
  "mailin8r.com", "mailinatar.com",
  "mailinater.com", "mailinator.com",
  "mailinator.net", "mailinator.org",
  "mailinator2.com", "mailincubator.com",
  "mailismagic.com", "mailjunk.org",
  "mailmate.com", "mailme.gq",
  "mailme.ir", "mailme.lv",
  "mailme24.com", "mailmetrash.com",
  "mailmoat.com", "mailmoth.com",
  "mailms.com", "mailnator.com",
  "mailnesia.com", "mailnull.com",
  "mailonaut.com", "mailorc.com",
  "mailorg.org", "mailox.fun",
  "mailpick.biz", "mailpooch.com",
  "mailproxsy.com", "mailquack.com",
  "mailrocket.biz", "mailsac.com",
  "mailscrap.com", "mailseal.de",
  "mailshell.com", "mailshiv.com",
  "mailsiphon.com", "mailslapping.com",
  "mailslite.com", "mailspam.xyz",
  "mailtemp.info", "mailtemporaire.com",
  "mailtemporaire.fr", "mailtome.de",
  "mailtothis.com", "mailtraps.com",
  "mailtrash.net", "mailtrix.net",
  "mailtv.net", "mailtv.tv",
  "mailuniverse.co.uk", "mailvpn.info",
  "mailwriting.com", "mailz.info",
  "mailzen.win", "mailzilla.com",
  "mailzilla.org", "makemenaughty.club",
  "makemetheking.com", "malahov.de",
  "malayalamdtp.com", "mama3.org",
  "mancity.net", "mandraghen.cf",
  "manifestgenerator.com", "mannawo.com",
  "marfino.su", "maricopa.com",
  "mariosur.it", "marshscale.com",
  "maskedmails.com", "maskmail.net",
  "maswae.world", "matamuasu.cf",
  "matchpolice.com", "materiali.ml",
  "max-mail.com", "mbox.re", "mbx.cc",
  "mciek.com", "mdhc.tk",
  "meantinc.com", "mebelnu.info",
  "mechanicalresumes.com", "medsheet.com",
  "meepsheep.eu", "meinspamschutz.de",
  "meltmail.com", "memsg.site",
  "merda.cf", "merda.ga", "merda.gq", "merda.ml", "merda.tk",
  "merry.pink", "messagebeamer.de",
  "mezimages.net", "mfsa.info", "mfsa.ru",
  "miaferrari.com", "midcoastcustoms.com", "midcoastcustoms.net",
  "midlertidig.com", "midlertidig.net", "midlertidig.org",
  "mierdamail.com", "migmail.net", "migmail.pl",
  "migumail.com", "mijnhva.nl",
  "ministry-of-silly-walks.de", "minsmail.com",
  "mintemail.com", "miraigames.net",
  "mirrorrr.asia", "mirrorrr.com",
  "misery.net", "misterpinball.com",
  "mji.ro", "mjukglass.nu",
  "mkpfilm.com", "ml8.ca",
  "mm.my", "mn.curppa.com",
  "mnode.me", "moakt.com", "moakt.ws",
  "mobileninja.co.uk", "mobilevpn.top", "moburl.com",
  "mockmyid.com", "moeri.org",
  "mohmal.com", "mohmal.im", "mohmal.in", "mohmal.tech",
  "momentics.ru", "moncourrier.fr.nf",
  "monemail.fr.nf", "moneypipe.net",
  "monmail.fr.nf", "monumentmail.com",
  "moonwake.com", "moot.es",
  "moreawesomethanyou.com", "moreorcs.com",
  "morriesworld.ml", "morsin.com",
  "mortmesttesre.win", "mosaicfx.com",
  "mostwantedbabes.com", "motique.de",
  "mountainregionallibrary.net", "mox.pp.ua",
  "moy-e-mail.com", "mozillafirefox.com",
  "mp3geau.ga", "mr24.co",
  "mrpost.com", "mrvpm.net",
  "msa.minsmail.com", "msgden.com",
  "msgos.com", "msgsafe.io",
  "mspeciosa.com", "msrc.ml",
  "mswork.ru", "msxd.com",
  "mt2009.com", "mt2014.com", "mt2015.com",
  "muehlacker.tk", "muell.icu",
  "muellmail.com", "muellemail.com",
  "mundodigital.net", "munoubengoshi.gq",
  "mupload.nl", "murchschool.org",
  "musclemailbox.com", "mustbe.ignorelist.com",
  "mustbedestroyed.org", "mutant.me",
  "muttvpn.net", "mwarner.org",
  "mx0.wwwnew.eu", "my-spam.net",
  "my.efxs.ca", "my10minutemail.com",
  "myalias.pw", "mycard.net.ua",
  "mycleaninbox.net", "mycorneroftheinter.net",
  "myde.ml", "myemailboxy.com",
  "myemaill.com", "mygeoweb.info",
  "myindohome.services", "myinterserver.ml",
  "mykickassideas.com", "mymail-in.net",
  "mymail90.com", "mymailoasis.com",
  "mymailto.xyz", "mynetstore.de",
  "myopang.com", "mypacks.net",
  "mypartyclip.de", "myphantomemail.com",
  "mysamp.de", "myspaceinc.com",
  "myspaceinc.net", "myspaceinc.org",
  "myspacepimporama.com", "myspamless.com",
  "mystvpn.com", "mytemp.email",
  "mytempemail.com", "mytruemail.net",
  "mywarnet.net", "myway.com",
  "myworldmail.com", "n2.com",
  "n2snow.com", "n8.gs",
  "naa.net", "nabuma.com",
  "nada.email", "nada.ltd",
  "nagarealm.com",
];

const MEDIUM_RISK_DOMAINS: string[] = [
  "mailmetrash.com",
  "mobileninja.co.uk",
  "mytrashmail.com",
  "neverbox.com",
  "nowmymail.com",
  "oneoffmail.com",
  "owlymail.com",
  "pookmail.com",
  "proxymail.eu",
  "quickinbox.com",
  "rcpt.at",
  "receiveee.com",
  "recyclemail.com",
  "regbypass.com",
  "sneakemail.com",
  "sofort-mail.de",
  "spamfree24.org",
  "spamherelots.com",
  "spamlot.net",
  "spamobox.com",
  "spamslicer.com",
  "spamthis.co.uk",
  "spamtrail.com",
];

export function getDisposableRisk(domain: string): "high" | "medium" | "none" {
  const lower = domain.toLowerCase().trim();
  if (HIGH_RISK_DOMAINS.includes(lower)) return "high";
  if (MEDIUM_RISK_DOMAINS.includes(lower)) return "medium";
  return "none";
}
 